const DISPLAY_ERROR_MESSAGE_BOOLEAN = 'DISPLAY_ERROR_MESSAGE_BOOLEAN';
const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';
const ERROR_CODE = 'ERROR_CODE';
const ERROR_RESPONSE = 'ERROR_RESPONSE';


export const errorHandlerConst = {
  DISPLAY_ERROR_MESSAGE_BOOLEAN,
  DISPLAY_ERROR_MESSAGE,
  ERROR_CODE,
  ERROR_RESPONSE,
};